### ISSUE TITLE
installation and setup instruction

### ISSUE THREAD

**Issue by eazuka** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#2]
Hi, i am interested in testing this project out. are there instructions somewhere?
does this just work or it has dependencies?

it will be nice and helpful if you can write-up a short installation and setup instructions.

**Comment by VISWESWARAN1998** [comment]
All you need is Python3 and selenium module installed along with your Python3 you can able to use this once it is done

**Comment by VISWESWARAN1998** [comment]
@eazuka All you need is Python3 and selenium module installed along with your Python3 you can able to use this once it is done

**Comment by CNajm** [comment]
@eazuka 
I was unable to run this successfully due to outdated xpaths but I have forked this project and improved and fixed it. 

I made the decision to split it from the fork since I saw myself steering the project in a different direction with mine majorly focusing on providing an efficient framework for bots and automated presence. You can find a full guide to running it there.

If you're interested, you can check it out here https://github.com/CNajm/Sych-WhatsApp

**Comment by VISWESWARAN1998** [comment]
@CNajm can you send me a pull request with a fix of new xpaths?

**Comment by VISWESWARAN1998** [comment]
@CNajm Issues addressed.
