### ISSUE TITLE
Getting usernames with unread messages not work

### ISSUE THREAD

**Issue by lordmurda** [VISWESWARAN1998/Simple-Yet-Hackable-WhatsApp-api#42]
from whatsapp import WhatsApp
whatsapp = WhatsApp(100, session="mysession")
print(whatsapp.unread_usernames(scrolls=100))

Hello, when I tried to run this code, I've got just [ ]
Bot doesn't see persons which has unread messages.
Maybe problem in Chrome version?

**Comment by VISWESWARAN1998** [comment]
I have checked and found that the class names has been outdated which I have fixed in the latest commit please check and let me know. 

If you think that the latest commit has addressed your issue kindly close the issue and feel free raise further issues and questions you have. 

Thank you!
Visweswaran N

**Comment by lordmurda** [comment]
Great, now it's working.
Thank you!
